<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Tehtävät on päivitetty',
    'Auth item with such name already exists' => 'Kyseisen niminen autentikointikohde on jo olemassa',
    'Children' => 'Lapset',
    'Class' => '',
    'Class "{0}" does not exist' => '"{0}" -luokkaa ei ole olemassa',
    'Create' => 'Luo',
    'Create new permission' => 'Luo uusi käyttöoikeus',
    'Create new role' => 'Luo uusi rooli',
    'Create rule' => '',
    'Created at' => '',
    'Data cannot be decoded' => '',
    'Data must be type of JSON ({0})' => '',
    'Description' => 'Kuvaus',
    'Enter the description' => '',
    'Invalid value' => 'Virheellinen arvo',
    'Item has been created' => 'Kohde on luotu',
    'Item has been updated' => 'Kohde on päivitetty',
    'Items' => 'Kohteet',
    'Name' => 'Nimi',
    'Name is already in use' => '',
    'New permission' => 'Uusi käyttöoikeus',
    'New role' => 'Uusi rooli',
    'New rule' => '',
    'New user' => 'Uusi käyttäjä',
    'Not found' => '',
    'Permissions' => 'Käyttöoikeudet',
    'Roles' => 'Roolit',
    'Rule' => 'Sääntö',
    'Rule class can not be instantiated' => 'Sääntö -luokasta ei voi luoda ilmentymää',
    'Rule class must extend "yii\\rbac\\Rule"' => '@@Sääntö -luokan pitää laajentaa "yii\\rbac\\Rule"@@',
    'Rule has been added' => '',
    'Rule has been removed' => '',
    'Rule has been updated' => '',
    'Rule name' => 'Säännön nimi',
    'Rule {0} does not exist' => '',
    'Rules' => '',
    'Save' => 'Tallenna',
    'Select permission' => '',
    'Select role' => '',
    'Select rule' => '',
    'There is neither role nor permission with name "{0}"' => '"{0}" -nimellä ei ole roolia eikä käyttöoikeutta',
    'Update assignments' => 'Päivitä tehtävät',
    'Update permission' => 'Päivitä käyttöoikeus',
    'Update role' => 'Päivitä rooli',
    'Update rule' => '',
    'Updated at' => '',
    'Users' => 'Käyttäjät',
];
