<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'اختیارات ویرایش شدند',
    'Auth item with such name already exists' => 'آیتمی با این نام وجود دارد',
    'Children' => '',
    'Class' => '',
    'Class "{0}" does not exist' => 'کلاس "{0}" وجود ندارد',
    'Create' => 'ایجاد',
    'Create new permission' => 'ایجاد دسترسی جدید',
    'Create new role' => 'ایجاد نقش جدید',
    'Create rule' => '',
    'Created at' => '',
    'Data cannot be decoded' => '',
    'Data must be type of JSON ({0})' => '',
    'Description' => 'توضیحات',
    'Enter the description' => '',
    'Invalid value' => 'مقدار نامعتبر',
    'Item has been created' => 'آیتم ایجاد شد',
    'Item has been updated' => 'آیتم ویرایش شد',
    'Items' => '',
    'Name' => 'نام',
    'Name is already in use' => '',
    'New permission' => 'دسترسی جدید',
    'New role' => 'نقش جدید',
    'New rule' => '',
    'New user' => 'کاربر جدید',
    'Not found' => '',
    'Permissions' => 'دسترسی ها',
    'Roles' => 'نقش ها',
    'Rule' => '',
    'Rule class can not be instantiated' => 'کلاس نقش قابل نمونه سازی نیست',
    'Rule class must extend "yii\\rbac\\Rule"' => '@@کلاس نقش باید از "yii\\rbac\\Rule" مشتق شود@@',
    'Rule has been added' => '',
    'Rule has been removed' => '',
    'Rule has been updated' => '',
    'Rule name' => 'نام نقش',
    'Rule {0} does not exist' => '',
    'Rules' => '',
    'Save' => 'ذخیره',
    'Select permission' => '',
    'Select role' => '',
    'Select rule' => '',
    'There is neither role nor permission with name "{0}"' => 'هیچ گونه نقش یا دستسری با نام "{0}" وجود ندارد',
    'Update assignments' => 'ویرایش اختیارات',
    'Update permission' => 'ویرایش دسترسی',
    'Update role' => 'ویرایش نقش',
    'Update rule' => '',
    'Updated at' => '',
    'Users' => 'کاربران',
];
