<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Assegnamenti aggiornati',
    'Auth item with such name already exists' => 'Esiste gi&agrave; un oggetto di autenticazione con questo nome',
    'Children' => '',
    'Class' => '',
    'Class "{0}" does not exist' => 'La classe "{0}" non esiste',
    'Create' => 'Crea',
    'Create new permission' => 'Crea un nuovo permesso',
    'Create new role' => 'Crea un nuovo ruolo',
    'Create rule' => '',
    'Created at' => '',
    'Data cannot be decoded' => '',
    'Data must be type of JSON ({0})' => '',
    'Description' => 'Descrizione',
    'Enter the description' => '',
    'Invalid value' => 'Valore non valido',
    'Item has been created' => 'Oggetto creato',
    'Item has been updated' => 'Oggetto aggiornato',
    'Items' => '',
    'Name' => 'Nome',
    'Name is already in use' => '',
    'New permission' => 'Nuovo permesso',
    'New role' => 'Nuovo ruolo',
    'New rule' => '',
    'New user' => 'Nuovo utente',
    'Not found' => '',
    'Permissions' => 'Permessi',
    'Roles' => 'Ruoli',
    'Rule' => '',
    'Rule class can not be instantiated' => 'Impossibile istanziare la classe delle regole',
    'Rule class must extend "yii\\rbac\\Rule"' => '@@La classe delle regole deve estendere "yii\\rbac\\Rule"@@',
    'Rule has been added' => '',
    'Rule has been removed' => '',
    'Rule has been updated' => '',
    'Rule name' => 'Nome regola',
    'Rule {0} does not exist' => '',
    'Rules' => '',
    'Save' => 'Salva',
    'Select permission' => '',
    'Select role' => '',
    'Select rule' => '',
    'There is neither role nor permission with name "{0}"' => 'Non esiste un ruolo o un permesso di nome "{0}"',
    'Update assignments' => 'Aggiorna assegnamenti',
    'Update permission' => 'Aggiorna permesso',
    'Update role' => 'Aggiorna ruolo',
    'Update rule' => '',
    'Updated at' => '',
    'Users' => 'Utenti',
];
