<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Роли были назначены',
    'Auth item with such name already exists' => 'Элемент с таким именем уже существует',
    'Children' => 'Включает в себя',
    'Class' => 'Класс',
    'Class "{0}" does not exist' => 'Класс "{0}" отсутствует',
    'Create' => 'Создать',
    'Create new permission' => 'Создать новое разрешение',
    'Create new role' => 'Создать новую роль',
    'Create rule' => 'Новое правило',
    'Created at' => 'Создано в',
    'Data cannot be decoded' => 'Невозможно декодировать данные',
    'Data must be type of JSON ({0})' => 'Данные должны быть представлены в JSON ({0})',
    'Description' => 'Описание',
    'Enter the description' => 'Введите описание или его часть',
    'Invalid value' => 'Неверное значение',
    'Item has been created' => 'Пункт был создан',
    'Item has been updated' => 'Пункт был обновлен',
    'Items' => 'Пункты',
    'Name' => 'Имя',
    'Name is already in use' => 'Это имя уже используется',
    'New permission' => 'Новое разрешение',
    'New role' => 'Новая роль',
    'New rule' => 'Новое правило',
    'New user' => 'Новый пользователь',
    'Not found' => 'Не найдено',
    'Permissions' => 'Разрешения',
    'Roles' => 'Роли',
    'Rule' => 'Правило',
    'Rule class can not be instantiated' => 'Объект класса правила не может быть создан',
    'Rule class must extend "yii\\rbac\\Rule"' => 'Класс правил должен быть наследником класса "yii\\rbac\\Rule"',
    'Rule has been added' => 'Правило было успешно добавлено',
    'Rule has been removed' => 'Правило было удалено',
    'Rule has been updated' => 'Правило было отредактировано',
    'Rule name' => 'Правило',
    'Rule {0} does not exist' => 'Правило {0} не найдено',
    'Rules' => 'Правила',
    'Save' => 'Сохранить',
    'Select permission' => 'Выберите разрешение',
    'Select role' => 'Выберите роль',
    'Select rule' => 'Выберите правило',
    'There is neither role nor permission with name "{0}"' => 'Не существует ни ролей ни разрешений с именем "{0}"',
    'Update assignments' => 'Обновить назначения',
    'Update permission' => 'Обновить разрешения',
    'Update role' => 'Обновить роль',
    'Update rule' => 'Обновить правило',
    'Updated at' => 'Отредактировано в',
    'Users' => 'Пользователи',
];
