<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Les affectations ont été mises à jour',
    'Auth item with such name already exists' => 'Un rôle/Une permission avec un nom identique existe déjà',
    'Children' => 'Rôles/Permissions rattaché(e)s',
    'Class' => '',
    'Class "{0}" does not exist' => 'La classe "{0}" n\'existe pas',
    'Create' => 'Créer',
    'Create new permission' => 'Créer une nouvelle permission',
    'Create new role' => 'Créer un nouveau rôle',
    'Create rule' => '',
    'Created at' => '',
    'Data cannot be decoded' => '',
    'Data must be type of JSON ({0})' => '',
    'Description' => 'Description',
    'Enter the description' => '',
    'Invalid value' => 'Valeur invalide',
    'Item has been created' => 'Le rôle/La permission a été créé(e)',
    'Item has been updated' => 'Le rôle/La permission a été mis(e) à jour',
    'Items' => 'Rôles/Permissions',
    'Name' => 'Nom',
    'Name is already in use' => '',
    'New permission' => 'Nouvelle permission',
    'New role' => 'Nouveau rôle',
    'New rule' => '',
    'New user' => 'Nouvel utilisateur',
    'Not found' => '',
    'Permissions' => 'Permissions',
    'Roles' => 'Rôles',
    'Rule' => 'Règle',
    'Rule class can not be instantiated' => 'La classe de règle ne peut pas être instanciée',
    'Rule class must extend "yii\\rbac\\Rule"' => '@@La classe de règle doit étendre "yii\\rbac\\Rule"@@',
    'Rule has been added' => '',
    'Rule has been removed' => '',
    'Rule has been updated' => '',
    'Rule name' => 'Nom de la règle',
    'Rule {0} does not exist' => '',
    'Rules' => '',
    'Save' => 'Sauvegarder',
    'Select permission' => '',
    'Select role' => '',
    'Select rule' => '',
    'There is neither role nor permission with name "{0}"' => 'Il n\'y a ni rôle, ni permission avec le nom "{0}"',
    'Update assignments' => 'Modifier les affectations',
    'Update permission' => 'Modifier la permission',
    'Update role' => 'Modifier le rôle',
    'Update rule' => '',
    'Updated at' => '',
    'Users' => 'Utilisateurs',
];
