<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Ролі були призначені',
    'Auth item with such name already exists' => 'Елемент з таким іменем вже існує',
    'Children' => 'Дочірні правила',
    'Class' => '',
    'Class "{0}" does not exist' => 'Клас "{0}" відсутній',
    'Create' => 'Створити',
    'Create new permission' => 'Створити новий дозвіл',
    'Create new role' => 'Створити нову роль',
    'Create rule' => '',
    'Created at' => '',
    'Data cannot be decoded' => '',
    'Data must be type of JSON ({0})' => '',
    'Description' => 'Опис',
    'Enter the description' => '',
    'Invalid value' => 'Неправильне значення',
    'Item has been created' => 'Елемент було створено',
    'Item has been updated' => 'Елемент було оновлено',
    'Items' => 'Елементи',
    'Name' => 'Ім\'я',
    'Name is already in use' => '',
    'New permission' => 'Новий дозвіл',
    'New role' => 'Нова роль',
    'New rule' => '',
    'New user' => 'Новий користувач',
    'Not found' => '',
    'Permissions' => 'Дозволи',
    'Roles' => 'Ролі',
    'Rule' => 'Правило',
    'Rule class can not be instantiated' => 'Об\'єкт класу правил не може бути створений',
    'Rule class must extend "yii\\rbac\\Rule"' => '@@Клас правил повинен наслідувати клас "yii\\rbac\\Rule"@@',
    'Rule has been added' => '',
    'Rule has been removed' => '',
    'Rule has been updated' => '',
    'Rule name' => 'Правило',
    'Rule {0} does not exist' => '',
    'Rules' => '',
    'Save' => 'Зберегти',
    'Select permission' => '',
    'Select role' => '',
    'Select rule' => '',
    'There is neither role nor permission with name "{0}"' => 'Не існує ні ролей, ні дозволів з іменем "{0}"',
    'Update assignments' => 'Оновлення призначення',
    'Update permission' => 'Оновити дозвіл',
    'Update role' => 'Оновити роль',
    'Update rule' => '',
    'Updated at' => '',
    'Users' => 'Користувачі',
];
