<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'As atribuições foram atualizadas',
    'Auth item with such name already exists' => 'O item Auth com este nome já existe',
    'Children' => 'Descendentes',
    'Class' => '',
    'Class "{0}" does not exist' => 'A classe "{0}" não existe',
    'Create' => 'Criar',
    'Create new permission' => 'Criar nova permissão',
    'Create new role' => 'Criar nova role',
    'Create rule' => '',
    'Created at' => '',
    'Data cannot be decoded' => '',
    'Data must be type of JSON ({0})' => '',
    'Description' => 'Descrição',
    'Enter the description' => '',
    'Invalid value' => 'Valor inválido',
    'Item has been created' => 'Item foi criado',
    'Item has been updated' => 'Item foi atualizado',
    'Items' => '',
    'Name' => 'Nome',
    'Name is already in use' => '',
    'New permission' => 'Nova permissão',
    'New role' => 'Nova role',
    'New rule' => '',
    'New user' => 'Novo usuário',
    'Not found' => '',
    'Permissions' => 'Permissões',
    'Roles' => 'Roles',
    'Rule' => 'Regra',
    'Rule class can not be instantiated' => 'A classe de regra não pode ser instanciada',
    'Rule class must extend "yii\\rbac\\Rule"' => '@@A classe de regra deve estender "yii\\rbac\\Rule"@@',
    'Rule has been added' => '',
    'Rule has been removed' => '',
    'Rule has been updated' => '',
    'Rule name' => 'Nome da regra',
    'Rule {0} does not exist' => '',
    'Rules' => '',
    'Save' => 'Salvar',
    'Select permission' => '',
    'Select role' => '',
    'Select rule' => '',
    'There is neither role nor permission with name "{0}"' => 'Não existe nem role nem permissão com o nome "{0}"',
    'Update assignments' => 'Alterações realizadas',
    'Update permission' => 'Alterar permissão',
    'Update role' => 'Alterar role',
    'Update rule' => '',
    'Updated at' => '',
    'Users' => 'Usuários',
];
